---
application:
    name: 'loopify-backend'
    project: 'Loopify'
    organization: 'QoveryCommunity'
routers:
    - name: 'main'
      routes:
          - application_name: 'loopify-backend'
            paths:
                - '/*'
